### ISSUE TITLE
Paslaugų damage

### ISSUE THREAD

**Issue by M0diis** [M0diis/MCSlime.LT-Issue-Tracker#11]
*Perkelta iš discord*

**Apibūdink klaidą**  
@ATAMANE

Gavau nusiskundimą, kad žaidėjas ,nusipirkęs gold paslaugą, gauna žalą nuo kaktusų, nors forumo paslaugų skiltyje rašoma, jog "kaktuso palietimas nedaro žalos". (tas pats galioja nardymui po vandeniu) 

**Nuotraukos**  
![image](https://user-images.githubusercontent.com/53468997/150234363-a5667520-a3f9-476d-bcb8-72044b7b35bf.png)

**Comment by M0diis** [comment]
@ciga

nezinau bugas ar ne, bet paslauginiai gauna damage nuo lavos, fire, tarkim legend paslauga sudega nethery,
silver paslauga turetu negaut fall damage, bet ja gauna

**Comment by Ciga** [comment]
谢谢~已收到！

**Comment by M0diis** [comment]
它不适合你。对不起。

**Comment by M0diis** [comment]
Galėtų gal kas ištestuot nuo Bronze-Legend (nebūtinai visus, būtų gerai bent vienas ar du) kaip nors, kurios apsaugos veikia, kurios ne?
