### ISSUE TITLE
Naujoko apsauga

### ISSUE THREAD

**Issue by M0diis** [M0diis/MCSlime.LT-Issue-Tracker#14]
*Perkelta iš discord*

@Cluelessas

žaidėjai su naujoko apsauga abusina /warp pvp vieta (manau kad ne tik warp pvp), kol turi /newbie apsaugą ta, eina i pvp duobę ir renkasi itemus. Tas pats ir su atsijungimu ir prisijungimu lyg.

**Comment by M0diis** [comment]
Variantas būtų padaryt, kad negalėtų įeit į PVP rezidencijas ir /warp pvp.

**Comment by Dzygius** [comment]
Manau užtektu padaryti, kad į /warp pvp negalėtu. Res'ai yra kiekvieno žmogaus infividualiai, ten jie tvarkosi patys. Yra komandos tp f move f. Nemanau kad ten reikėtų kišti nagus.

**Comment by M0diis** [comment]
Klaida sutvarkyta, turėtų viskas veikt po serverio perkrovimo.

Apibendrinant:
- Žaidėjas su išjungtu PvP režimu negalės įeit į `/warp pvp`.
- Žaidėjas su naujoko apsauga negalės įeit į `/warp pvp`.
