### ISSUE TITLE
Rezidencijų mokestis

### ISSUE THREAD

**Issue by M0diis** [M0diis/MCSlime.LT-Issue-Tracker#16]
*Perkelta iš discord*

@Cluelessas

Už pačio res turėjimą padaryti savaitinį mokestį ir jai ten 3 savaites iš eilės nesumoka už res (nebūtinai 3) res būtų pašalinimas, taip būtų išvengiama nenaudojamų res + būtų šiek tiek apsunkinta serverio ekonomika.

**Comment by M0diis** [comment]
Nelabai verta daryt, nes jei koks žaidėjas su daug turto ilgai neprisijungs - praras jį. 
Taip kitiems būtų lengva pasipelnyt.

**Comment by Cluelessas** [comment]
nu bet jai i mėn karta neprisijungia tai nemanau kad dar jis daugiau žaist, aišku galima prailgint ta laika per kurį bus ištrinamas res.

**Comment by M0diis** [comment]
Perkeliu modelt atsakymą:

ideja gera, bet pvz: tokie zaidejai kurie turi dideli turta ir pamirsta prisijungti menesi gera arba trumpam palieka serveri. t.y noriu pasakyti, kad prasides tokiu resu medziokle. Zaidejai nores lengvu budu praturteti
na nezinau. +- esu tiek ir uz, tiek ir pries
nuo tada niekaip neapsisprendziu del resu auto-remove

**Comment by Cluelessas** [comment]
o tai šita komanda nesusijusi su tuo mokesčiu ?
![image](https://user-images.githubusercontent.com/98104993/150587951-0ec33578-bd10-4fd5-a925-b8a611627db1.png)

**Comment by M0diis** [comment]
ne. čia išnuomavimas rezidencijos kitam žaidėjui.

**Comment by Dzygius** [comment]
60d off ir ate resui. 2mėnesiai yra jau per ilga pertrauka

**Comment by M0diis** [comment]
> 60d off ir ate resui. 2mėnesiai yra jau per ilga pertrauka

Eina tokią funkciją įjungt, kažkada planavom, bet modė taip ir neįjungė niekad.

**Comment by M0diis** [comment]
Paklausk modės dėl šito. Įjungsiu, jei sutikimą duos.

**Comment by Dzygius** [comment]
> Paklausk modės dėl šito. Įjungsiu, jei sutikimą duos.

Modelt: galima daryti, bet naikinant res'a būtų padaroma //set 0. T.y. kad nebūtų likusių daiktų jokių.

**Comment by M0diis** [comment]
nu čia tas `//set 0` nelabai įmanomas.
jeigu ir būtų įmanoma, kaip atrodytų 50x50 duobės, kur net bedrock neliktų.

**Comment by Cluelessas** [comment]
storint reso block info ( nu tipo kai resas sukurtas ta visa nukopijuot) ir kai res buna pasalinamas grazintu tuos pradinius blokus.

**Comment by M0diis** [comment]
Rezidencijos dydis gali būt keičiamas. Per daug informacijos reiktų saugot ir keist.
Tiesiog per daug darbo dėl tokios paprastos problemos.
Du mėnesius neaktyviam būt ir taip sunkiai įmanoma, ir jeigu viduryj tarp 4 mėnesių, tada jau niekaip tie resai nebus ištrinti, nes greičiau bus wipe.
