### ISSUE TITLE
subzone pasalinimas, kai atsiranda naujas res savininkas.

### ISSUE THREAD

**Issue by Cluelessas** [M0diis/MCSlime.LT-Issue-Tracker#20]
**Apibūdink klaidą**  
Kai žmogus parduoda res su res market ar perduodamas res, dažniausiai buna paliekami subzone ir neperduodami tam zaidėjui.

**Kaip klaida įvyko**
Žmonės pirkdami res ne karta yra nukentėja kai nusipirkus res buna like subzone.

**Papildoma informacija**  
Manau kad problema būtų galima pašalint automatiškai ištrinant subzone.

**Comment by M0diis** [comment]
Nežinau ar būtų gera mintis ištrinti tas subzonas, bet gal ir nebūtų labai didelė problema.

**Comment by Cluelessas** [comment]
nu tipo jai tik ant hopper padaro subzone, žaidėjas tikrai nepastebės

**Comment by M0diis** [comment]
Ištestuokit ar subzonos pašalinamos, kai rezidencija perduodama kitam savininkui.

T.y. subzonos bus ištrintos kai rezidencija bus nuperkama arba perduodama su /res give.

**Comment by M0diis** [comment]
Buvo patvirtinta, kad viskas tvarkoje.
