### ISSUE TITLE
Unban nerodymas /hist troter, nežinau ar ir ant kitu žaidėju hist nerodo unbanu

### ISSUE THREAD

**Issue by Cluelessas** [M0diis/MCSlime.LT-Issue-Tracker#21]
**Apibūdink klaidą**  
Nerodo unban po bano.

**Kaip klaida įvyko**
/hist troter nerodo unbano.

**Vaizdinė medžiaga**  
![image](https://user-images.githubusercontent.com/98104993/150583862-b30e2c47-2146-45d9-be7d-b1d81319d9ed.png)

**Comment by Cluelessas** [comment]
taip pat ir su /hist loftas

**Comment by M0diis** [comment]
Irrelevant, uždarau.
