### ISSUE TITLE
Admin Panel 

### ISSUE THREAD

**Issue by Justas27** [M0diis/MCSlime.LT-Issue-Tracker#22]
Admin Panel klaidos.

Šiuo atveju klaida čia: https://mcslime.lt/discord/staffcard.php

Ar begalime tikėtis pabaigtos Admin Panel versijos? Idomus dalykas su pakankamai potencialo tapti naudingu įrankiu.

<img width="1440" alt="Screenshot 2022-01-22 at 15 02 29" src="https://user-images.githubusercontent.com/98216840/150639850-dacc4eb0-09b9-41ec-befe-faefa6e8158b.png">

**Comment by M0diis** [comment]
Žinau šituos dalykus.
Tiesiog su dabartinėmis turimomis galimybėmis sunku kažką padaryt, nes forumo sistemoj negaliu instaliuot composer, nei discord-php.
Tenka dirbt tu `curl`, bet su juo nelabai įmanoma gaut vartotojo roles serveryje.

**Comment by M0diis** [comment]
Nu, dabar sutvarkyta.
Dėl features dar not sure, kokie bus.

**Comment by M0diis** [comment]
![image](https://user-images.githubusercontent.com/53468997/150644154-5f17b907-8956-4712-a043-4781a4c5a210.png)

Pridėjau vartotojo informaciją, tik nežinau, ką galima būtų joje rašyt.

**Comment by Justas27** [comment]
Gal prie vartotojo informacijos pridėti galimybę matyti koks rank° serveryje ir paskutinis gautas ban/mute

_°eilinis, hero, chatmod, admin ir t.t._

**Comment by M0diis** [comment]
Pridėjau pilną užblokavimų ir užtildymų istoriją.
Tikiuosi dar pavyks įdėt užblokavimą ir užtildymą tiesiai iš sistemos.

**Comment by M0diis** [comment]
Klaida kaip ir sutvarkyta.
Atnaujinimai bus su savu laiku.
