### ISSUE TITLE
/kapitonaskey bugas.

### ISSUE THREAD

**Issue by Cluelessas** [M0diis/MCSlime.LT-Issue-Tracker#23]
**Apibūdink klaidą**  
Žaidėjas tik pasikėlęs iki kapitono ranko, bei parašęs /kapitonaskey komandą gavo zinutę, jog jis jau buvo pasiėmęs kapitonaskey. (tai įvyko maždaug šios dienos 15:35-15:55 laike), reikia patikrint ar tikrai tuo metu jis pasikėlė rank ir bandė imt kapitononas key tačiau jam metė cooldowną. Su co l patikrinau ar jis nepasiėme kapitonas key per pastarąją valandą.
**Kaip klaida įvyko**
Kaip ir sakiau, žaidėjas pasikėlė rank iki kapitono ir parašęs /kapitonaskey, jam išmetė cooldowną.
**Vaizdinė medžiaga**  
![image](https://user-images.githubusercontent.com/98104993/150641771-82be2902-b913-47f8-b32e-b6cd12adba62.png)

**Papildoma informacija**  
Taip pat buvo įvykis ir anksčiau su kapitonaskey, su kuriuo susitvarkiau pats prašydamas modelt jam duoti raktą, kurio jis negavo.

**Comment by M0diis** [comment]
Čia lyg užskaito cooldowną, jeigu neturėdamas rank bando pasiimt raktą.

**Comment by Cluelessas** [comment]
needs fix then

**Comment by M0diis** [comment]
Neturėjo permission reikalavimo komanda, dėl to leisdavo rašyt ir užskaitydavo kaip cooldown.
Sutvarkyta.
