### ISSUE TITLE
Chestsell nerf (pardavimo kainos sumažinimas naudojantis chestsell)

### ISSUE THREAD

**Issue by Cluelessas** [M0diis/MCSlime.LT-Issue-Tracker#24]
**Ar šis pasiūlymas išspręs kokią nors problemą? Parašyk tikslų apibūdinimą.**  
Manau kad tai pasunkintu patį žaidimą ir žaidėjai parduodantys su chestsell gautų mažesnį pelną.

**Pasiūlymo alternatyvos**  
alternatyvų kaip ir nėra.

**Papildoma informacija**  
manau jog, pamažinus kiekvieno daikto pardavimą kokiais 5% būtų pakankamai geras sumažinimas.

**Kokio tipo šis pasiūlymas**  
 Atnaujinimas: esamos funkcijos atnaujinimas, patobulinimas.

**Comment by M0diis** [comment]
Dėl šito sutikčiau.

Kelios nerf idėjos:
- Kiekvieno parduodamo daikto pardavimo kainą sumažint X proc.
- Nuskaičiuot X proc. nuo gautos sumos, po pardavimo.
- Uždėt kainą už kiekvieno ženklo sukūrimą.

**Comment by Dzygius** [comment]
Kaip kokia valstybė, viską apmokestinti...

**Comment by Cluelessas** [comment]
neapmokestinti tiesiog sis dalykas ganėtinai stipriai palengvina visa pardavimą ir manau, kad žaidėjai tai vis tiek naudos.

**Comment by Dzygius** [comment]
Jo, todėl tu ir moki 500k už šitą dalyką...

**Comment by M0diis** [comment]
Nukelta kitam wipe.
