### ISSUE TITLE
Komanda leidžianti pažiūrėti savo playtime per visus wipe.

### ISSUE THREAD

**Issue by Cluelessas** [M0diis/MCSlime.LT-Issue-Tracker#25]
**Ar šis pasiūlymas išspręs kokią nors problemą? Parašyk tikslų apibūdinimą.**  
Vienas žaidėjas buvo klausęs ar būtų įmanoma pažėti kiek laiko jis yra išviso per visus wipe pražaidęs ant to acc, žinau kad tokios komandos nėra, tačiau manau, kad žaidėjam būtų visai įdomu pažiūrėti savo visa pražaistą laika.

**Kokio tipo šis pasiūlymas**  
Nauja funkcija: visiškai nauja funkcija ar dalykas.

**Comment by M0diis** [comment]
Nelabai įmanoma, nes saugomi tik praeito wipe duomenys.

**Comment by Cluelessas** [comment]
Nu tada labai liūdna, kad neišeis, o kopijuojant sistema ir tiesiog pritaikant ja visu wipe neišeitų ? (tiesiog įsitikinimui klausiu).

**Comment by M0diis** [comment]
Nelabai įmanomas dalykas, kadangi, kaip minėjau, informacija nėra saugoma iš wipe į wipe.

Pasiūlymą uždarau.
