### ISSUE TITLE
Dropper minigame

### ISSUE THREAD

**Issue by Cluelessas** [M0diis/MCSlime.LT-Issue-Tracker#26]
Tikslus ir aiškus pasiūlymo aprašymas.
Taigi, siūlau pridėti dropper eventą į serverį. Būtų pristatyta 40 (nebūtinai 40) dropper žemėlapių (vietų kur šoks žemyn), 40 todėl, kad žaidėjai neišmoktų atmintinai kur kaip šokt. Galima ir pasiskolinti iš interneto dropper mapų. Bei manau kad pažiūrėję dropper minigame video geriau suprasite koks yra evento tikslas.
Pridėk papildomą informaciją, nuotraukas ar kt. čia.
Video linkas : https://www.bing.com/videos/search?q=dropper+minigame&&view=detail&mid=B5A36C3F0A0716B79D5FB5A36C3F0A0716B79D5F&&FORM=VRDGAR&ru=%2Fvideos%2Fsearch%3Fq%3Ddropper%2Bminigame%26FORM%3DHDRSC4

**Kokio tipo šis pasiūlymas**  
  
  
Naujas funkcija: visiškai nauja funkcija ar dalykas.

**Comment by M0diis** [comment]
Būtų galima padaryt /warp dropper event pasaulyje, ir iš HUB kokio teleportuotis į skirtingas vietas.

O dėl pačių mapų, jei įjungtas flat world, galit ten statyt.

**Comment by Beqnoi** [comment]
![Ekrano nuotrauka 2022-01-23 173506](https://user-images.githubusercontent.com/98063437/150686177-6f415855-0c41-4a33-bedb-099ff0cdbe04.png)

Išjungtas /warp flat

**Comment by patrikbrah** [comment]
Tikslesnis pavadinimas būtų gravity (/warp gravity), tačiau idėja tikrai nebloga, būtų vis kažkas naujo, nei tos pačios /warp spalvos.

**Comment by Cluelessas** [comment]
o tai kaip dėl pačių gravity vietų, jei mes neturim galimybės įeiti į /warp flat, bei manau ir b chatmodai, bei chatmodai turėdami laiko norėtų prisidėti prie statymo( jai patys statysim), ar iš interneto kopijuosim ? (btw buvau matęs kur su command block automatiškai random dropper vieta pastato, tačiau tai tikrai nebūtų estetiškai gražu).

**Comment by M0diis** [comment]
Turėtų eit įeit į flat pasaulį.(/warp flat)
Bet liks tik pagalbom, betkuriuo atveju.

**Comment by M0diis** [comment]
Nu kaip ir turim jau `/warp dropper`. 
Visada bus galima papildyt. Šiam kartui uždarau.
