### ISSUE TITLE
Leisti ant savo alt uždėti fly, god ir invis

### ISSUE THREAD

**Issue by Cluelessas** [M0diis/MCSlime.LT-Issue-Tracker#27]
**Ar šis pasiūlymas išspręs kokią nors problemą? Parašyk tikslų apibūdinimą.**  
Žaidėjai tiesiog prideda mus prie savo kill auros draugų, ir tai labai pasunkina cheaterių gaudymą, tad leisdami mums tai padaryti, mes galėtume per savo alt prie ju nuskristi ir patikrinti.
Alternatyvos:
sukurti papildomus acc su tam tikrais permission, kuriuos galėtų naudoti bet kuri pagalba, tačiau jai kas leakintu žaidėjai greitai galėtų juos pridėt prie savo kill auros draugų.
**Papildoma informacija**  
šiuo metu visi žaidėjai žino, kad mes dažniausiai cheaterius gaudome per savo main acc, todėl jiems lengva išvengti mūsų tikrinimo su /invis, kai jie eina pvp.

**Kokio tipo šis pasiūlymas**  
  
  
 Nauja funkcija: visiškai nauja funkcija ar dalykas.

**Comment by Beqnoi** [comment]
Prieš 100%, tikrai atsiras pagalbų kurios pradės abusint

**Comment by Cluelessas** [comment]
padaryt kad tik ant to pacio ip leistu

**Comment by M0diis** [comment]
Nebent sukurt atskirą paskyrą(-as) su fake legend, kad nebūtų jokių papildomų privilegijų ir uždėt IP apsaugą, kad nebūtų galima paleakint slaptažodžio ir bet kam prisijungt.

**Comment by Beqnoi** [comment]
Arba nebent kaip tigeris kažkada minėjo, apie nežymėtą pagalba, kuri kažkaip užsimaskavus gaudo hackerius

**Comment by M0diis** [comment]
Gal būt kadanors reikės grįžt prie šito pasiūlymo, bet šiuo metu nemanau, kad naudingas dalykas.
