### ISSUE TITLE
/vanish

### ISSUE THREAD

**Issue by Velnias1** [M0diis/MCSlime.LT-Issue-Tracker#28]
**Apibūdink klaidą**  
Aiškus klaidos aprašymas. Išėjus iš /v, /vanish išsijungia /fly

**Comment by M0diis** [comment]
Tiesiog taip paprastai? Gan keista. Nelabai galiu patestuot šito dalyko.

**Comment by M0diis** [comment]
Pasitikslinau su modelt, klaida buvo dėl kito vanish plugin.

Turėtų veikt kaip įprasta.
Klaidą uždarau.
