### ISSUE TITLE
Laikas

### ISSUE THREAD

**Issue by Beqnoi** [M0diis/MCSlime.LT-Issue-Tracker#32]
**Ar šis pasiūlymas išspręs kokią nors problemą? Parašyk tikslų apibūdinimą.**  
Toks gal ir nedidelis pasiūlymas, bet paspaudus tab nevisada matosi laikas, taip lengvoka apgauti, išspręstu problemą nuo apgaudinėjimo, nežinia ar yra tokių kurie bandė taip apgaudinėti, bet apsisaugoti nėra niekada per vėlu. Pagalvojau pasiūlyti pakeisti tab rodymą į kokią komandą, arba sutvarkyti laiką tab'e, nes per vaizdo įrašus nevisada matosi laikas paspaudus tab

**Pasiūlymo alternatyvos**  
Parašius kokia komandą pvz /laikas ar kažkas tokio rodytų datą, laiką ir t.t., arba tiesiog padaryti, kad paspaudus tab kažkurioje vietoje visada matytųsi laikas

**Kokio tipo šis pasiūlymas**  
Atnaujinimas: esamos funkcijos atnaujinimas, patobulinimas.

**Comment by M0diis** [comment]
TAB lengviau paspaust nei komandą parašyt, tai manau geriau tiesiog įdėt į TABą.

**Comment by M0diis** [comment]
Sutvarkyta.
