### ISSUE TITLE
SB vertimas

### ISSUE THREAD

**Issue by patrikbrah** [M0diis/MCSlime.LT-Issue-Tracker#33]
**Apibūdink klaidą**  
SB Vertimas

**Kaip klaida įvyko**
Nesulietuvintos vietos. ↓
                                     

- [x] Missions (/is missions)

- [x] Spawn'e salos valdymas. (TIK salos patobulinimas!)

- [x] Weird menu

**Vaizdinė medžiaga**  
Misijos https://imgur.com/a/OoqtAes
Salos patobulinimas (spawn'e) https://imgur.com/a/QrS9chu
Menu https://imgur.com/a/QCkPn2N

**Papildoma informacija**  
pridėsiu komentaruose, jei rasiu daugiau.

**Comment by Dzygius** [comment]
Salos patobulinimas sutvarkyti.
