### ISSUE TITLE
/shop naudojimas tik turint tam privilegija

### ISSUE THREAD

**Issue by Cluelessas** [M0diis/MCSlime.LT-Issue-Tracker#34]
**Ar šis pasiūlymas išspręs kokią nors problemą? Parašyk tikslų apibūdinimą.**  
Manau kad /shop sutaupo per  pernelyg daug laiko žaidėjam ir yra tikrai labai stipriai palengvinantis žaidimą dalykas, taigi manau kad /shop reiktu leisti naudoti tik paspaudus ant /shop vilagerio, nebent žaidėjas turi privilegiją leidžiančia jam tai daryti. Privilegija naudoti /shop butų galima gauti nusipirkus paslaugą nuo bronze arba perkant iš pačio /shop

**Kokio tipo šis pasiūlymas**  
  
Atnaujinimas: esamos funkcijos atnaujinimas, patobulinimas.

**Comment by M0diis** [comment]
Nuėmiau leidimus pradiniams lygiams, VIP ir aukščiau turės galimybę naudotis nuotoline parduotuve.
Manau reiktų padaryt tą patį ir su aukcionu?

**Comment by Dzygius** [comment]
Turi omenyje, kad tik >VIP galės rašyti komandas /ah /shop, o visi kiti turės eiti per villargerį?
dėl /ah sutinku pilnai, o dėl /shop dalinai sutinku, bet nebus per daug verkimų?

**Comment by Dzygius** [comment]
Padaryta
