### ISSUE TITLE
Pridėjimas some kind of enchant plugin

### ISSUE THREAD

**Issue by Cluelessas** [M0diis/MCSlime.LT-Issue-Tracker#35]
ir sb ir main servui
**Ar šis pasiūlymas išspręs kokią nors problemą? Parašyk tikslų apibūdinimą.**  
Tikslus ir aiškus pasiūlymo aprašymas.
Jau nuo senu laiku xp fermos būdavo nuvertinamos ir nenaudojamos, tačiau pridėjus some kind of enchant plugina manau, kad pagyvintumėte xp fermas ( daugiau veiklos žaidėjam bandant gauti geriausius enchantus).

**Kokio tipo šis pasiūlymas**  
  
 Naujas funkcija: visiškai nauja funkcija ar dalykas.

**Comment by M0diis** [comment]
Turime savo pluginą.
