### ISSUE TITLE
Sugalvot paslaugas pirkimui apart VIP, S-VIP, M-VIP.

### ISSUE THREAD

**Issue by M0diis** [M0diis/MCSlime.LT-Issue-Tracker#38]
Reikia sugalvot paslaugas, kurias būtų galima nusipirkti SkyBlock serveryje.

**Comment by Dzygius** [comment]
Paslaugų privilegijos: P.S. Iš pradžių ne taip supratau temą. Bet netrinsiu privilegijų.
MVIP - Fly, repair(cd5-10m), repair all(cd 30m), shop'e viskam 7% discount, /kit, 2raktai Skurdi ir 1raktas gera ir 1 legendary,
SVIP - Chestsell, repair(cd15-30m), shop'e viskam 5% discount, /kit, 2raktai Skurdi ir 1raktas gera,
VIP - heal, feed, nightvision, shop'e viskam 2% discount, /kit, 2raktai Skurdi,

P.S. Raktai gaunami tik vieną kartą, nusipirkus.

Gal net padaryti, kad paslaugas galėtų nusipirkti, 14d 30d arba visam wipe? Atitinkamai ir kainos. 14d - 60% 30d-100% Viso wipe kaina - 3-4mėn kaina?

Papildomos paslaugos: 
Raktų pirkimas(Skurdi,gera,legendary)

Chestsell (Visam wipe) Kaina 5-10e. Taip pat galėtų gauti iš paslaugos, bet ta privilegija galiotu 30d tik. P.S. Reikėtų užtikrinti, kad nusipirkus chestsell ir poto paslaugą. Paslaugai pasibaigus, turėtų chestsell. Taip pat bus galimybė pačiam serveryje nusipirkti /chestsell.

Salos padidinimo galimybės: 50 100 150. Taip pat būtų ir žaidime, bet mažesnės: 50 75 100.

Salos žaidėjų didinimo galimybė. Dabar regis max gali būti 5. Parduoti paslaugą kuri iškarto atrakintu iki 7-8 žaidėjų. Ekonomikos negadina visiškai, kaina nebūtinai didelė.

Padaryti 4 generatoriaus lygi kurį nusipirktu tik iš paslaugų ir saloje turėtų būti atrakintas 3lvl jau. P.S. Nežinau kiek sunkiai surišti šiuos 2 dalykus...

Realiai visi salos upgrades, tik kad čia būtų geresni. Bet kaip ir anksčiau turėtų būti pasiekę max'a salose, kad galėtų nusipirkti. Nebus P2W, o bus papildomas upgrade jei nori įsiveržti į priekį.

Čia jau P2W gal gaunasi, bet įdėti kit'a kuriame būtų spawnerių ir t.t. Už 10e mėnesiui arba visam wipe. CD būtų 6-7d Reikėtų pasistengti subalansuoti. Turėtų apsimokėti labiau nei nupirkti iškart spawnerius. 

P.S. Nemanau, kad spawner turėtu būti pardavinėjami paslaugose. Too ez. arba nebent lievi spawner pig/cow. Ir spawneriu negalės keisti. Kokį tipą gavo tokį jau gavo.

**Comment by M0diis** [comment]
Trumpai pakomentuoju vieną dalyką.
Tikrint ar jau turi X upgrade su dabartine sistema yra neįmanoma. Geriau jau tebūnie pirkt balansą ir atsirakint patiems.

**Comment by Dzygius** [comment]
Bet tada visi galės, nebelieka privilegijos :/ Nu supratau

**Comment by M0diis** [comment]
Privilegijos jau yra. 
Issue uždarau.
