### ISSUE TITLE
prob both: naudojant f3 g pvz ant lunaro ir laby mod launcher rodo skirtingas chunk vietas

### ISSUE THREAD

**Issue by Cluelessas** [M0diis/MCSlime.LT-Issue-Tracker#39]
**Apibūdink klaidą**  
visa bėda apibūdinta title skiltyje
**Vaizdinė medžiaga**  

**Papildoma informacija**  
https://imgur.com/a/BdtoRkZ
Jei reikia - parašyk papildomą informaciją čia.
idk ar tai fixable, nes kiek žinau ir singleplayer taip rodo

**Comment by M0diis** [comment]
Už third-party client klaidas ar neatitikimus neatsakau.

**Comment by Cluelessas** [comment]
o tai nebutu galima padaryt kad su komanda rodytu servo chunkus ?

**Comment by Beqnoi** [comment]
Tikrinau su 3 launcheriais, lunar, labymod ir paprastu mc, labymod ir paprastas mc rodė vienodai, tai kaip suprantu su lunaru problemos čia

**Comment by M0diis** [comment]
Dar kart kartoju, klaidų ar nesutapimų, kurios atsiranda naudojant third-party client`us ir kurias galima išspręst naudojant vanilla - netaisysiu. 
Nėra tam laiko.
