### ISSUE TITLE
pvp dėžių abusinimas su atsijungimu pvp dežėje

### ISSUE THREAD

**Issue by Cluelessas** [M0diis/MCSlime.LT-Issue-Tracker#40]
**Apibūdink klaidą**  
Žaidėjai prieš einant 1v1 i dėžę paprašo draugo, jog atsijungtų pvp dėžėje, tad siūlau pridėti tokį dalyka kaip teleportinima į spawną jei žaidėjas atsijungė pvp zonoje.
**Kaip klaida įvyko**
Jau ne pirmą karta žaidėjai man skundėsi dėl tokių atsitikimų.
**Papildoma informacija**  
manau kad žaidėjai kurie eina i /warp pvp galėtų abusint šiuo updeitu, tad padaryt, kad tik is resu, kuriuose įjungtas  pvp on, telintų i spawną.

**Comment by M0diis** [comment]
Šiaip už veiklą žaidėjų rezidencijose atsako patys žaidėjai.
Gali eit į kitą areną.

**Comment by Cluelessas** [comment]
gal gali pasakyt kaip žaidėjai gali nuo to apsisaugot savo pvp resuose, nes bet kurioje viešoje pvp arenos 1v1 dėžėje gali atsijungt ir prisijungus eit ne 1v1 kaip tarėsi, o 2v1 :/ + /res set tp f  nepaveikia to atsijungimo ir prisijungimo.

**Comment by M0diis** [comment]
Įdėtas /duel.
