### ISSUE TITLE
/newbietime neissijungia

### ISSUE THREAD

**Issue by Cluelessas** [M0diis/MCSlime.LT-Issue-Tracker#41]
**Apibūdink klaidą**  
Žaidėjai pradėjo skustis, jog newbietime neišsijungia , vieni iš žaidėjų JKUP ir Saltukas_ .

**Comment by Cluelessas** [comment]
ok, jau kazkaip eina pvp pamineti zaidejai :/

**Comment by M0diis** [comment]
Ilgas laikas nustatytas.
