### ISSUE TITLE
Pridėti dar viena kanala prie mcslime discord : Memes

### ISSUE THREAD

**Issue by Cluelessas** [M0diis/MCSlime.LT-Issue-Tracker#45]
**Ar šis pasiūlymas išspręs kokią nors problemą? Parašyk tikslų apibūdinimą.**  
Tikslus ir aiškus pasiūlymo aprašymas.
Kaip jau matote nuotrauku kanalas tapo uzfloodintas chato zinutemis, kurios visai grozio neturi, tad manau reiktu tam sukurt memu kanalą, bei neturint ka veikt patys galetume pakimarint dc kanale ziurint memus atsiustus kitų žaidėjų

Alternatyva butu prideti serverio perliukai.

**Kokio tipo šis pasiūlymas**  
  
Atnaujinimas: esamos funkcijos atnaujinimas, patobulinimas.

**Comment by M0diis** [comment]
Nežinau kiek naudingas šis dalykas. Būdavo off-topic, nebuvo labai naudojamas. 
Vėl gi reiktų prižiūrėt nuo totalių nesąmonių ir vėl klausimas ar leist/neleist **visiems** kelt nuotraukas ar tik su role.

**Comment by M0diis** [comment]
Nenaudinga, nebus.
