### ISSUE TITLE
Ban PVP metu

### ISSUE THREAD

**Issue by M0diis** [M0diis/MCSlime.LT-Issue-Tracker#5]
*Perkelta iš discord*

@Cluelessas
Pasiūlymas- išimti taisykle jog negalim banint pvp metu nebent duobėje, manau, kad jai žaidėjas cheatina yra pats kaltas, jog praranda itemus, kurie yra jo inventoriuje.

**Comment by Dzygius** [comment]
Sužinosiu iš modelt informaciją. Jei jam tiks, galėsim baninti pvp metu.

**Comment by Dzygius** [comment]
Modelt:
cheatinant, tai jau pofig.

**Comment by Dzygius** [comment]
Jei cheatina, galima baninti, nepriklausomai ar žaidėjas yra pvp režime.
