### ISSUE TITLE
global on, off

### ISSUE THREAD

**Issue by GytulisLTU** [M0diis/MCSlime.LT-Issue-Tracker#51]
/am - global on, global off sukeisti vietom

https://streamable.com/31qc8s

**Comment by M0diis** [comment]
Kažkada jau buvo kalba apie šitą.

Esmė tokia, kad „GLOBAL ON = RANGED OFF“ ir vise versa.

Jeigu prisiruošiu - sutvarkysiu.

**Comment by M0diis** [comment]
Sutvarkyta.
