### ISSUE TITLE
/ranks - Tab

### ISSUE THREAD

**Issue by GitWireless** [M0diis/MCSlime.LT-Issue-Tracker#53]
**Ar šis pasiūlymas išspręs kokią nors problemą? Parašyk tikslų apibūdinimą.**  
Gaunu klausimų iš žaidėjų, kaip sužinoti, kiek kainuoja rank's. Šiuo metu yra dvi komandos, su kuriomis gali pažiūrėti visus rank's _/ranks_ ir _/rankslist_, bet kiek žinau jos nerodo kiek kainuoja rankai. Galima pažiūrėti kiek kainuoja tik parašius _/pareigunas_ "atidaro lentelę" spaudi "atgal" ir rodo visus ranks, kits loot, kainą rank's. Siūlau pašalinti chat informaciją apie rank's ir pašalinti _/rankslist_, o parašius _/ranks_ išmestų lentelę kuri jau yra.

**Papildoma informacija**  
![Screenshot_15](https://user-images.githubusercontent.com/101657504/161623615-08d0d8c7-c837-4db4-b398-350e42dbc1b1.png)
![Screenshot_16](https://user-images.githubusercontent.com/101657504/161623658-03ef227a-b06c-4592-b35c-8086047d6b22.png)

**Kokio tipo šis pasiūlymas**  
Atnaujinimas: esamos funkcijos atnaujinimas, patobulinimas.

**Comment by M0diis** [comment]
Tiksliai nepamenu, bet lyg yra komanda `/rank`, kuri atidaro tą meniu antroj nuotraukoj.

**Comment by GitWireless** [comment]
Jo, patikrinau yra, bet galėtų būti ši vienintelė lentelė su viena komanda, būtų clean.

**Comment by M0diis** [comment]
Nelabai yra ką tvarkyt.

Yra kelios komandos, žaidėjai randa manau.
