### ISSUE TITLE
Paslaugos

### ISSUE THREAD

**Issue by Kornelija135** [M0diis/MCSlime.LT-Issue-Tracker#54]
**Ar šis pasiūlymas išspręs kokią nors problemą? Parašyk tikslų apibūdinimą.**  
Tikslus ir aiškus pasiūlymo aprašymas.
Prie /paslaugos pridėti unbanip,spawner raktas.
/paslaugos -> Setai  (neatitinka kaina)

Manau mažiau žmonės painiosis dėl neatitikimų, paslaugų info trūkumo žaidime.

**Pasiūlymo alternatyvos**  
Tikslūs ir aiškus alternatyvų aprašymas, jei tokių yra.
Pridėti tam tikras paslaugas, atnaujinti kainas

**Papildoma informacija**  
Pridėk papildomą informaciją, nuotraukas ar kt. čia.

![setai 2](https://user-images.githubusercontent.com/103922184/166565748-7ceb7dac-1cc0-4e6f-bdc0-8d44d16bf5b1.png)

![setai 1](https://user-images.githubusercontent.com/103922184/166565762-69b38a2d-d55d-44f1-bd79-c76a5d67b859.png)

**Kokio tipo šis pasiūlymas**  
Atnaujinimas.

**Comment by M0diis** [comment]
Klaida sutvarkyta.

Įdėti placeholderiai, kurie automatiškai paims duomenis iš paslaugų sistemos ir atvaizduos žaidime.
`%mcslime_paslaugos_kaina_<paslaugos-pavadinimas>%`
