### ISSUE TITLE
plow infinity bug

### ISSUE THREAD

**Issue by patrikbrah** [M0diis/MCSlime.LT-Issue-Tracker#57]
**Apibūdink klaidą**  
bug'as su plow, infinity seedai, kai juos pervadini

**Kaip klaida įvyko**
pervadini seedus ir gali sodint kiek nori, jų nemažėja

**Vaizdinė medžiaga**  
https://streamable.com/5yubp8

**Papildoma informacija**  
solution, papraščiausiai uždrausti pervadinti seed'us.

**Comment by M0diis** [comment]
Sutvarkyta.
