### ISSUE TITLE
duel bug

### ISSUE THREAD

**Issue by patrikbrah** [M0diis/MCSlime.LT-Issue-Tracker#58]
**Apibūdink klaidą**  
Bug'as su /duel

**Kaip klaida įvyko**
Kai esi /duel su kitu žaidėjų, kitas galį šaudyti su lanku ir gausi damage. (nors neturėtu nei vienas negalėti tave pažeisti, tik priešininkas)

**Vaizdinė medžiaga**  
https://streamable.com/mk2z51

**Comment by M0diis** [comment]
Reikia patikrint, ar susitvarkė.

**Comment by Kornelija135** [comment]
Pratestinom, susitvarkė. https://streamable.com/xh8ggg
