### ISSUE TITLE
Holograma

### ISSUE THREAD

**Issue by Beqnoi** [M0diis/MCSlime.LT-Issue-Tracker#61]
**Apibūdink klaidą**  
Hologramos wild'e

**Kaip klaida įvyko**
Skraidžiau ir radau

**Vaizdinė medžiaga**  
![2022-05-26_11 08 41](https://user-images.githubusercontent.com/98063437/170447415-bd9ae06c-9baf-49f4-b1d0-8a8f0a137ee3.png)

**Papildoma informacija**  
Hologramų kordinatės XYZ 350 67 -200

**Comment by M0diis** [comment]
Sutvarkyta.
